config/routes.rb
Rails.application.routes.draw do
  root to: 'urls#new'
  resources :urls, only: [:create, :show]
  get '/:article', to: 'urls#redirect'
end

app/models/url.rb
class Url < ActiveRecord::Base

  def self.find_by_path(path)

  end


  def self.top_100
  query = <<-SQL
    SELECT
      url, short, visits
    FROM
      urls
    ORDER BY
      visits DESC
    LIMIT 100

    SQL

    Url.find_by_sql(query)
  end

  def url
    self[:url]
  end

  def add_visit
    self[:visits] += 1
    self.save!
  end

  def self.shorten(id)
    special = "$-_+!*'(),".split("")
    chars = special.concat(('a'..'z').to_a).concat(('A'..'Z').to_a).concat(('0'..'9').to_a)
    indices = []
    num = id.to_i
    while num > 0
      remainder = num % 72
      indices.push(remainder)
      num = num / 72
    end
    indices.reverse!
    short = indices.map {|idx| chars[idx]}.join
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception




end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController

  def show
    # redirect_to 'http://www.google.com'
  end

  def redirect
    path = params[:article]
    url = Url.where(short: path)[0]
    url.add_visit
    redirect = url.url

    if redirect.include?("http://") || redirect.include?("https://")
      redirect_to redirect
    else
      redirect_to 'http://' + redirect
    end
  end

  def create
    @url = Url.create!(url_params)
    short = Url.shorten(@url.id)
    @url[:short] = short

    if @url.save!
      render :show
    else
      redirect_to :show
    end

  end

  def new
    @url = Url.new
    render :new
  end

  private

  def url_params
    params.permit(:url)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>URLShort</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>URL Shortener</h1>
<%= yield %>

<h3>Top 100 URLs</h6>
<div class="table">
  <table>
    <tr>
      <th>
        Rank
      </th>
      <th>
        Short Url
      </th>
      <th>
        Visits
      </th>
    </tr>
    <% Url.top_100.each_with_index do |url, idx| %>
      <tr>
        <td>
        <%= idx + 1 %>
        </td>
        <td>
          <a target="_blank" href="<%= url.short %>">shortshorts.herokuapp.com/<%= url.short %></a>
        </td>
        <td>
          <%= url.visits %>
        </td>
      </tr>
    <% end %>
  </table>

</div>

</body>
</html>

app/views/urls/new.html.erb
 <div class="">
   <form class="" action="<%= urls_url %>" method="post">

    <label for="url"> <strong>Enter your URL:</strong </label>
    <br>
    <input type="text" name="url" value="">
    <!-- <textarea name="url" rows="8" cols="40"></textarea> -->
    <button type="submit" name="button">Shorten Url</button>

  </form>

 </div>

app/views/urls/show.html.erb
<h2>Shortened URL:</h2>

<h3>shortshorts.herokuapp.com/<%= @url.short %></h3>

<a href="<%= root_url %>">Make a new Url</a>